---
name: shortcut_whats
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  url_launcher: ^5.6.0
  equatable: ^1.2.5
  sqflite: ^1.3.1+1
  firebase_admob: ^0.9.3+4
  shimmer: ^1.1.1
  share: ^0.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/
